https://github.com/kashyap1808/assignment

language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - pwd
  - mkdir public
  - ls -la

install:
  - ls -la
  - npm install
  - ls -la
